apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: feature-branch-janitor
  annotations:
    test: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
         run: feature-branch-janitor
    spec:
      containers:
        - name: fb-janitor 
          image: feature-branch-janitor:$VERSION
          imagePullPolicy: Never
